version: "3.9"

services:
  api:
    build:
      context: .
      target: production
    ports:
      - 8000:8000
    env_file:
      - .env
    command: pdm run uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
      - redis
  
  worker:
    build:
      context: .
      target: production
    env_file:
      - .env
    command: pdm run celery -A worker.celery worker --loglevel=info    
    depends_on:
      - redis
  
  postgres:
    image: postgres:15.3-bookworm
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:7.0-bookworm
    ports:
      - 6379:6379
    env_file:
      - .env
    